"""
Generate a bash script that moves or copies STEP files into cluster folders.

The generated script is intended to be copied to a NAS and run there, so this
Python file only reads clusters.json and writes shell commands.
"""
import argparse
import json
import shlex
from pathlib import Path
from typing import Dict, List


STEP_EXTS = [".step", ".stp", ".STEP", ".STP"]


def load_json(path: Path):
    with open(path, "r", encoding="utf-8-sig") as fp:
        return json.load(fp)


def normalize_clusters(data) -> List[Dict]:
    if isinstance(data, dict):
        return [data]
    return data


def q(value: str) -> str:
    return shlex.quote(str(value))


def cluster_label(cluster_id: int) -> str:
    return f"{cluster_id:04d}"


def build_bash_script(clusters: List[Dict], step_dir: str, output_dir: str, move_files: bool = True) -> str:
    action_name = "move" if move_files else "copy"
    copy_only = "0" if move_files else "1"
    ext_values = " ".join(q(ext) for ext in STEP_EXTS)

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# Generated by move_step_by_cluster.py. Default action: {action_name}.",
        "# Set DRY_RUN=1 before running to print commands without changing files.",
        f"STEP_DIR={q(step_dir)}",
        f"OUTPUT_DIR={q(output_dir)}",
        f"COPY_ONLY={copy_only}",
        f"STEP_EXTS=({ext_values})",
        'MISSING_FILE="$OUTPUT_DIR/missing_steps.txt"',
        "MISSING_COUNT=0",
        "",
        "run_cmd() {",
        '    if [[ "${DRY_RUN:-0}" == "1" ]]; then',
        "        printf '[DRY_RUN]'",
        "        printf ' %q' \"$@\"",
        "        printf '\\n'",
        "    else",
        '        "$@"',
        "    fi",
        "}",
        "",
        "record_missing() {",
        "    local stem=$1",
        '    if [[ "${DRY_RUN:-0}" != "1" ]]; then',
        "        printf '%s\\n' \"$stem\" >> \"$MISSING_FILE\"",
        "    fi",
        "    MISSING_COUNT=$((MISSING_COUNT + 1))",
        "}",
        "",
        "find_step_file() {",
        "    local base_dir=$1",
        "    local stem=$2",
        "    local ext candidate",
        '    for ext in "${STEP_EXTS[@]}"; do',
        '        candidate="$base_dir/$stem$ext"',
        '        if [[ -f "$candidate" ]]; then',
        "            printf '%s\\n' \"$candidate\"",
        "            return 0",
        "        fi",
        "    done",
        "    return 1",
        "}",
        "",
        "place_cluster_file() {",
        "    local cluster_id=$1",
        "    local stem=$2",
        '    local cluster_dir="$OUTPUT_DIR/cluster_$cluster_id"',
        "    local src_file dst_file",
        "",
        '    if ! src_file=$(find_step_file "$STEP_DIR" "$stem"); then',
        '        echo "Missing STEP: $stem"',
        '        record_missing "$stem"',
        "        return 0",
        "    fi",
        "",
        '    dst_file="$cluster_dir/${src_file##*/}"',
        '    if [[ "$COPY_ONLY" == "1" ]]; then',
        '        run_cmd cp -p -- "$src_file" "$dst_file"',
        "    else",
        '        run_cmd mv -- "$src_file" "$dst_file"',
        "    fi",
        "}",
        "",
        "copy_representative() {",
        "    local cluster_id=$1",
        "    local stem=$2",
        '    local cluster_dir="$OUTPUT_DIR/cluster_$cluster_id"',
        '    local result_dir="$OUTPUT_DIR/result"',
        "    local rep_file dst_file",
        "",
        '    if ! rep_file=$(find_step_file "$cluster_dir" "$stem"); then',
        '        if ! rep_file=$(find_step_file "$STEP_DIR" "$stem"); then',
        '            echo "Missing representative STEP: $stem"',
        '            record_missing "$stem"',
        "            return 0",
        "        fi",
        "    fi",
        "",
        '    dst_file="$result_dir/cluster_${cluster_id}_${rep_file##*/}"',
        '    if [[ -f "$dst_file" ]]; then',
        "        return 0",
        "    fi",
        '    run_cmd cp -p -- "$rep_file" "$dst_file"',
        "}",
        "",
        'run_cmd mkdir -p "$OUTPUT_DIR" "$OUTPUT_DIR/result"',
        'if [[ "${DRY_RUN:-0}" != "1" ]]; then',
        '    : > "$MISSING_FILE"',
        "fi",
        "",
    ]

    for cluster in clusters:
        label = cluster_label(int(cluster["cluster_id"]))
        cluster_files = cluster["files"]
        representative = cluster["representative"]

        lines.extend(
            [
                f"# cluster_{label}",
                f'run_cmd mkdir -p "$OUTPUT_DIR/cluster_{label}"',
            ]
        )
        for fn in cluster_files:
            lines.append(f"place_cluster_file {q(label)} {q(fn)}")
        lines.append(f"copy_representative {q(label)} {q(representative)}")
        lines.append("")

    lines.extend(
        [
            'if [[ "$MISSING_COUNT" -gt 0 ]]; then',
            '    echo "Missing STEP entries: $MISSING_COUNT (see $MISSING_FILE)"',
            "else",
            '    echo "All STEP files processed."',
            "fi",
            "",
        ]
    )
    return "\n".join(lines)


def write_text_lf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf8", newline="\n") as fp:
        fp.write(text)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a pure-bash move/copy script according to clusters.json"
    )
    parser.add_argument("--clusters", type=str, required=True, help="clusters.json 路径")
    parser.add_argument("--step-dir", type=str, required=True, help="NAS 上的 STEP 文件目录")
    parser.add_argument("--output", type=str, required=True, help="NAS 上的输出目录")
    parser.add_argument("--copy-only", action="store_true", help="生成复制命令，不移动原文件")
    parser.add_argument(
        "--script-output",
        type=str,
        default=None,
        help="生成的 bash 脚本路径，默认写到 clusters.json 同目录",
    )
    args = parser.parse_args()

    clusters_path = Path(args.clusters)
    script_output = (
        Path(args.script_output)
        if args.script_output is not None
        else clusters_path.parent / "move_step_by_cluster.sh"
    )

    clusters = normalize_clusters(load_json(clusters_path))
    script = build_bash_script(
        clusters,
        step_dir=args.step_dir,
        output_dir=args.output,
        move_files=not args.copy_only,
    )
    write_text_lf(script_output, script)
    print(f"Generated bash script: {script_output}")
    print("Copy it to the NAS and run it with: bash move_step_by_cluster.sh")
    print("Preview without changing files: DRY_RUN=1 bash move_step_by_cluster.sh")


if __name__ == "__main__":
    main()
